[build]
command = """
ldd --version &&
mkdir functions &&
cargo build --release &&
ldd target/release/tracker &&
cp target/release/tracker functions/ 
"""

[functions]
directory = "functions/"

[functions.tracker]
schedule = "@hourly"
