[build]
command = """
echo done
"""
# command = """
# ldd --version &&
# mkdir functions &&
# cargo build --release &&
# cp target/release/tracker functions/ 
# cp target/release/tracker-url functions/ 
# """

[functions]
directory = "functions/"

[functions.tracker]
schedule = "@hourly"
